const express = require("express");

const app = express();

function requestLoggerMiddleware(req, res, next) {
  console.log(`${new Date()} - ${req.method} request received`);
  next();
}

app.use(requestLoggerMiddleware);

app.get("/", (req, res) => {
  res.send("This Web Page Is Generated By Mohit Agrawal For Learning Purpose");
});

app.listen(3000, () => {
  console.log("Server is running on port 3000");
});
